//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisPackers
{
    using System;
    using System.Collections.Generic;
    
    public partial class mockRefAuctionType
    {
        public int AuctionTypeID { get; set; }
        public string AuctionTypeDescription { get; set; }
        public bool AuctionTypeDeleted { get; set; }
        public bool AuctionTypeDefault { get; set; }
    }
}
