//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisPackers
{
    using System;
    using System.Collections.Generic;
    
    public partial class mockClient
    {
        public int ClientID { get; set; }
        public string TitleID { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public Nullable<int> PrimaryAddID { get; set; }
        public Nullable<int> DeliveryAddID { get; set; }
        public Nullable<int> BillingAddID { get; set; }
        public string TelephoneOther { get; set; }
        public string TelephoneMobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Comments { get; set; }
        public bool FreeCatalogue { get; set; }
        public string SageBuyerID { get; set; }
        public string SageVendorID { get; set; }
        public string OnlineVectisID { get; set; }
        public string OnlineEbayID { get; set; }
        public Nullable<bool> ContactEmail { get; set; }
        public Nullable<bool> ContactPost { get; set; }
        public Nullable<bool> ContactTelephone { get; set; }
        public Nullable<bool> ContactSMS { get; set; }
        public Nullable<decimal> DefaultCommBuyer { get; set; }
        public Nullable<decimal> DefaultCommVendor { get; set; }
        public string DefaultVatRate { get; set; }
        public Nullable<bool> UsePrimaryForBilling { get; set; }
        public Nullable<bool> UsePrimaryForDelivery { get; set; }
        public bool Deleted { get; set; }
        public bool Sendnewsletter { get; set; }
        public bool BidLiveChecked { get; set; }
        public bool BidProxyChecked { get; set; }
    }
}
