//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLot
    {
        public int CustomerLotId { get; set; }
        public int PackerId { get; set; }
        public int CustomerId { get; set; }
        public int LotId { get; set; }
        public Nullable<System.DateTime> DatePicked { get; set; }
        public Nullable<System.DateTime> DatePacked { get; set; }
        public bool ToyFair { get; set; }
    
        public virtual Packer Packer { get; set; }
    }
}
