//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PackerEntities : DbContext
    {
        public PackerEntities()
            : base("name=PackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerAuctionState> CustomerAuctionStates { get; set; }
        public virtual DbSet<CustomerLot> CustomerLots { get; set; }
        public virtual DbSet<Packer> Packers { get; set; }
    }
}
