//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string LogoLocation { get; set; }
        public string Colour1 { get; set; }
        public string Colour2 { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    }
}
