//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotKeyword
    {
        public int ID { get; set; }
        public string SearchTerm { get; set; }
        public string KeywordString { get; set; }
        public bool IsRegex { get; set; }
    }
}
