//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QNRGroup
    {
        public int QNRGroupID { get; set; }
        public int QNRID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupOrder { get; set; }
    }
}
