//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        public int QNRID { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Restricted { get; set; }
        public Nullable<bool> UniqueOnly { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public string Thankyoutext { get; set; }
    }
}
