//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public int QNRGroupID { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
        public string Text { get; set; }
        public string HelpText { get; set; }
        public string Regex { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Required { get; set; }
        public string REGEXErrorMessage { get; set; }
    }
}
