//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SagePayPayment
    {
        public int SagePayPaymentID { get; set; }
        public Nullable<int> LinkID { get; set; }
        public string VPSProtocol { get; set; }
        public string TxType { get; set; }
        public string Vendor { get; set; }
        public string VendorTxCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public string Token { get; set; }
        public string CardHolder { get; set; }
        public string CardNumber { get; set; }
        public string StartDate { get; set; }
        public string ExpiryDate { get; set; }
        public string IssueNumber { get; set; }
        public string CV2 { get; set; }
        public string CardType { get; set; }
        public string BillingSurname { get; set; }
        public string BillingFirstname { get; set; }
        public string BillingAddr1 { get; set; }
        public string BillingAddr2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingPostcode { get; set; }
        public string BillingCountry { get; set; }
        public string BillingState { get; set; }
        public string BillingPhone { get; set; }
        public string DeliverySurname { get; set; }
        public string DeliveryFirstname { get; set; }
        public string DeliveryAddr1 { get; set; }
        public string DeliveryAddr2 { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryPostcode { get; set; }
        public string DeliveryCountry { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryPhone { get; set; }
        public string PayPalCallbackURL { get; set; }
        public string CustomerEMail { get; set; }
        public string Basket { get; set; }
        public Nullable<bool> GiftAid { get; set; }
        public Nullable<int> ApplyAVSCV2 { get; set; }
        public string ClientIPAddress { get; set; }
        public Nullable<int> Apply3DSecure { get; set; }
        public string AccountType { get; set; }
        public Nullable<int> BillingAgreement { get; set; }
        public string Status { get; set; }
        public string StatusDetail { get; set; }
        public string VPSTxID { get; set; }
        public string SecurityKey { get; set; }
        public Nullable<int> TxAuthNo { get; set; }
        public string AVSCV2 { get; set; }
        public string AddressResult { get; set; }
        public string PostCodeResult { get; set; }
        public string CV2Result { get; set; }
        public string C3DSecureStatus { get; set; }
        public string CAVV { get; set; }
        public string C3DSecureMD { get; set; }
        public string CustomerRef { get; set; }
        public int WorkflowStatus { get; set; }
        public Nullable<bool> StoreToken { get; set; }
    }
}
