//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuctionDay
    {
        public int AuctionID { get; set; }
        public short DayNo { get; set; }
        public System.DateTime AuctionDateTime { get; set; }
        public string DayRangeText { get; set; }
        public int DayRangeMin { get; set; }
        public int DayRangeMax { get; set; }
        public int NextRoomPaddle { get; set; }
        public int NextPhonePaddle { get; set; }
        public bool VendorInvoicesProduced { get; set; }
        public bool BuyerInvoicesProduced { get; set; }
        public Nullable<decimal> RoomSaleCommRate { get; set; }
        public Nullable<decimal> DefaultVATRate { get; set; }
        public bool AuctionComplete { get; set; }
        public string OnlineTitle { get; set; }
        public string ViewingText { get; set; }
        public string RestartCache { get; set; }
    }
}
