//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAudit
    {
        public int AuditId { get; set; }
        public string AuditCategory { get; set; }
        public string AuditCode { get; set; }
        public string AuditSeverity { get; set; }
        public string AuditNote { get; set; }
        public System.DateTime AuditStamp { get; set; }
        public string IPAddress { get; set; }
    }
}
