//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public string UserName { get; set; }
        public string Identifier { get; set; }
    }
}
