//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBid
    {
        public long BidID { get; set; }
        public int AuctionID { get; set; }
        public long LotID { get; set; }
        public int BuyerID { get; set; }
        public System.DateTime BidDate { get; set; }
        public Nullable<decimal> BidValue { get; set; }
        public bool CommisionBid { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string DeletedReason { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Winning { get; set; }
        public string BidIPAddress { get; set; }
    
        public virtual tblAuction tblAuction { get; set; }
        public virtual tblClient tblClient { get; set; }
        public virtual tblLot tblLot { get; set; }
    }
}
