//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCatAux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCatAux()
        {
            this.tblLots = new HashSet<tblLot>();
        }
    
        public int CatAuxID { get; set; }
        public int CatAuxAuctionID { get; set; }
        public string CatAuxTitle { get; set; }
        public string CatAuxDesc { get; set; }
        public System.DateTime CatAuxCreateDate { get; set; }
        public int CatAuxWho { get; set; }
        public bool CatAuxImported { get; set; }
        public bool CatAuxRemoved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLot> tblLots { get; set; }
    }
}
