//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCollectionType
    {
        public int CollectionID { get; set; }
        public int CollectionTypeID { get; set; }
        public Nullable<System.DateTime> AuctionDate { get; set; }
    
        public virtual tblCollection tblCollection { get; set; }
        public virtual tblRefCollectionType tblRefCollectionType { get; set; }
    }
}
