//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDataFeed
    {
        public int FeedId { get; set; }
        public Nullable<System.DateTime> FeedDate { get; set; }
        public string FeedType { get; set; }
        public Nullable<int> RecordsInFeed { get; set; }
        public Nullable<int> RecordsOutstanding { get; set; }
        public string Status { get; set; }
    }
}
