//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail_Alerts
    {
        public int EID { get; set; }
        public string FromAddr { get; set; }
        public string ToAddr { get; set; }
        public string CCAddr { get; set; }
        public string bccAddr { get; set; }
        public string ESubject { get; set; }
        public string EBody { get; set; }
        public string EAttachments { get; set; }
        public Nullable<System.DateTime> ESentDate { get; set; }
        public Nullable<bool> ESentFlag { get; set; }
        public string Etype { get; set; }
        public bool EHtmlFormat { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
