//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLotBid
    {
        public int AuctionId { get; set; }
        public long LotId { get; set; }
        public int BuyerId { get; set; }
        public System.DateTime BidDate { get; set; }
        public decimal BidValue { get; set; }
        public string BidIPAddress { get; set; }
    }
}
