//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllAuctionView
    {
        public int ViewID { get; set; }
        public Nullable<System.Guid> SessionGUID { get; set; }
        public string Page { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> AuctionID { get; set; }
        public Nullable<int> DayNo { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> Sub { get; set; }
        public Nullable<int> lotID { get; set; }
    }
}
