//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewsletterClient
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int NewsletterId { get; set; }
        public bool IsSent { get; set; }
        public string NewslaterTemplate { get; set; }
    }
}
