//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int ClientID { get; set; }
        public Nullable<int> CCType { get; set; }
        public string CCNo { get; set; }
        public string CCHolderName { get; set; }
        public string CCExpiry { get; set; }
        public string CCStart { get; set; }
        public string CCSecurityNo { get; set; }
        public string CCIssueNo { get; set; }
        public string SageVendorID { get; set; }
        public string SageBuyerID { get; set; }
        public string BankHoldersName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankSortCode { get; set; }
        public bool UseCardForPayment { get; set; }
        public string PaymentToken { get; set; }
        public Nullable<bool> IsOldCreditCardDetails { get; set; }
        public Nullable<bool> IsInitialPaymentMade { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
