//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaddle
    {
        public int PaddleID { get; set; }
        public int AuctionID { get; set; }
        public int DayNo { get; set; }
        public int ClientID { get; set; }
        public int PaddleNo { get; set; }
        public int PaddleType { get; set; }
        public bool AccountSettled { get; set; }
        public string Lots { get; set; }
        public bool Deleted { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
