//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRefBidIncrement
    {
        public decimal MinRange { get; set; }
        public Nullable<decimal> MaxRange { get; set; }
        public decimal BidIncrement { get; set; }
    }
}
