//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRefCreditCardType
    {
        public int CreditCardTypeID { get; set; }
        public string Name { get; set; }
        public string SystemKeyword { get; set; }
        public int DisplayOrder { get; set; }
        public bool Deleted { get; set; }
        public decimal Charge { get; set; }
    }
}
