//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubscription
    {
        public int ClientID { get; set; }
        public Nullable<bool> SubAllDiecast { get; set; }
        public Nullable<bool> SubLead { get; set; }
        public Nullable<bool> SubDinky { get; set; }
        public Nullable<bool> SubTinplate { get; set; }
        public Nullable<bool> SubMatchbox { get; set; }
        public Nullable<bool> SubDolls { get; set; }
        public Nullable<bool> SubCorgi { get; set; }
        public Nullable<bool> SubGenToy { get; set; }
        public Nullable<bool> SubTrainRugby { get; set; }
        public Nullable<bool> SubGenTrain { get; set; }
        public string SubComment { get; set; }
        public Nullable<int> SubCredits { get; set; }
        public Nullable<bool> SubFree { get; set; }
        public Nullable<System.DateTime> SubLapsedDate { get; set; }
    }
}
