//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecUser
    {
        public int UserID { get; set; }
        public string LoginName { get; set; }
        public string Title { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string JobTitle { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Ext { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public bool Enabled { get; set; }
        public int WrkGroupId { get; set; }
    }
}
