//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaleInvoice()
        {
            this.tblSaleBuyers = new HashSet<tblSaleBuyer>();
            this.tblSaleVendors = new HashSet<tblSaleVendor>();
        }
    
        public int SaleInvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> AuctionID { get; set; }
        public Nullable<int> DayNo { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> CCType { get; set; }
        public string CCNo { get; set; }
        public string CCHolderName { get; set; }
        public string CCExpiry { get; set; }
        public string CCStart { get; set; }
        public string CCSecurityNo { get; set; }
        public string CCIssueNo { get; set; }
        public Nullable<decimal> CCAmount { get; set; }
        public Nullable<decimal> Postage { get; set; }
        public Nullable<decimal> PostVat { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public string DespatchNumber { get; set; }
        public string DespatchService { get; set; }
        public Nullable<decimal> CreditCharge { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateGenerated { get; set; }
        public Nullable<System.DateTime> DateAmended { get; set; }
        public Nullable<System.DateTime> DateEmailed { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public Nullable<bool> IsHammerPaid { get; set; }
        public Nullable<bool> IsFeesPaid { get; set; }
        public Nullable<decimal> CreditCardChargeRate { get; set; }
        public Nullable<decimal> PostageCCCharge { get; set; }
        public Nullable<decimal> PostageCCChargeRate { get; set; }
        public Nullable<decimal> HammerPayment { get; set; }
        public Nullable<decimal> CreditChargeOn { get; set; }
        public Nullable<bool> IsOnlineSaleIncluded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleBuyer> tblSaleBuyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleVendor> tblSaleVendors { get; set; }
    }
}
