//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSayuFeedUser
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ModifideDate { get; set; }
        public string ModCode { get; set; }
        public Nullable<int> SayuFeedCode { get; set; }
        public string Description { get; set; }
        public Nullable<long> FKID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int Status { get; set; }
        public int Status2 { get; set; }
    }
}
