//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSession
    {
        public System.Guid SessionGUID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> VisitStarted { get; set; }
    }
}
