//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTelephoneLotInterest
    {
        public int PaddleID { get; set; }
        public int AuctionID { get; set; }
        public long LotId { get; set; }
        public int ClientID { get; set; }
    }
}
