//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_tblWebUsers
    {
        public int WebUserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Enabled { get; set; }
        public int SecUserId { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool BidLive { get; set; }
        public bool BidProxy { get; set; }
        public float TermsVerAccepted { get; set; }
        public bool SecurityLocked { get; set; }
        public Nullable<System.DateTime> SecurityLockDate { get; set; }
        public bool NotifyOutbidEmail { get; set; }
        public bool NotifyOutbidSMS { get; set; }
        public int AltCurrencyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
