//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectisDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_tblCurrency
    {
        public int CurrencyId { get; set; }
        public string CurrencyDesc { get; set; }
        public string CurrencyTag { get; set; }
        public string CurrencySymbol { get; set; }
        public double CurrencyExchangeRate { get; set; }
        public Nullable<System.DateTime> CurrencyExchangeRateDate { get; set; }
        public bool CurrencyDefault { get; set; }
    }
}
